@APIURL=http://localhost:4000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJtYW5vakBnbWFpbC5jb20iLCJyb2xlIjoiQWRtaW4iLCJpYXQiOjE3ODQxMTA4NDMsImV4cCI6MTc4NDcxNTY0M30.9lOsJxwrvCRAFhykz7Jm5-MldtajgViSEfyN7HhrDUs

###
GET {{APIURL}}

###
POST {{APIURL}}/auth/register
Content-Type: application/json

{
  "fname": "Student",
  "lname": "student",
  "email": "student@gmail.com",
  "password": "12345678"
}

###
POST {{APIURL}}/auth/login
Content-Type: application/json

{
  "email": "manoj@gmail.com",
  "password": "password"
}

###
GET {{APIURL}}/auth/profile

###
GET {{APIURL}}/visitors
Authorization: Bearer {{token}}
