@APIURL=http://localhost:3000

###
GET {{APIURL}}

###
POST {{APIURL}}/auth/register
Content-Type: application/json

{
  "fname": "Manoj",
  "lname": "Thakur",
  "email": "manoj@gmail.com",
  "password": "password"
}

###
POST {{APIURL}}/auth/login
Content-Type: application/json

{
  "email": "manoj@gmail.com",
  "password": "password"
}
